### ISSUE TITLE
Ore Dictionary entries not being applied consistently

### ISSUE THREAD

**Issue by WesCook** [jaredlll08/CraftTweaker#162] opened 2017-02-21 16:58 UTC
#### Issue Description:
Ore dictionary entries entries are not being applied as expected.  Removals have no effect, and additions do not consistently show the updated recipe in JEI.

#### What happens:
When removing an ore dictionary entry from an item, that item continues to list recipes for that ore dictionary.  It does not appear to be applied at all.

When adding an ore dictionary entry to an item, it only appears to work after an `/mt reload` is used.  Relaunching the game normally does not apply the change.  In this state, JEI will show the recipes in the `R` mode, but does not show them in the `U` mode.

This may be related to this issue: https://github.com/mezz/JustEnoughItems/issues/742

#### What you expected to happen:
I expect oredict removals to remove that item from oredict-based recipes, and additions to show consistently.

#### Script used

Covers both examples of an addition working inconsistently, and a removal not working at all.

http://pastebin.com/veyTNQGH

#### Minetweaker.log file

http://pastebin.com/H0m7jTvh
____
#### Affected Versions

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2185
- Crafttweaker: 1.10.2-3.0.20
- JEI: Both 10.2-3.14.6.412 (latest beta) and 1.10.2-3.14.5.406 (latest release)

#### Your most recent log file where the issue was present: 

http://pastebin.com/bZ7tVYfK

**Comment by drakray** [comment] 2017-02-25 16:44
I came to report that as well, maybe the problem is bad syncing/refresh with JEI?

**Comment by darkhax** [comment] 2017-03-06 20:46
This seems like a duplicate of #142 and several other issues we have had with load order and JEI. This issue however should be resolved once #142 is also resolved.

**Closed by darkhax** 2017-03-06 20:46 UTC
