### ISSUE TITLE
[Crash] Crash when renaming things.

### ISSUE THREAD

**Issue by nikkimas** [jaredlll08/CraftTweaker#35] opened 2016-07-20 22:19 UTC
Got this [Crash](http://pastebin.com/VG9h5s3n) on the server after adding the rename parts of [this ](http://pastebin.com/XCv6FP3j) code (line 18 and 22)

**Comment by Carrots4U** [comment] 2016-08-01 21:41
I have a somewhat similar problem with renaming items, except instead of crashing the name of the item doesn't change even after a client restart, Here's the script relating to the name changes, http://pastebin.com/RH4bRjaa. The weird part is the minetweaker log does not even mention changing any item names, only the recipe additions/removals of my other stuff.

**Comment by jaredlll08** [comment] 2016-09-19 09:16
@nikkimas I'm going need you to update minetweaker and I need your full minetweaker.log and scripts

**Comment by jaredlll08** [comment] 2016-09-19 09:18
@Carrots4U your issue is a completely different issue but I'll get it fixed hopefully

**Comment by jaredlll08** [comment] 2016-09-19 10:13
@Carrots4U the issue is fixed, will be in the next version

**Comment by jaredlll08** [comment] 2016-09-30 17:46
@nikkimas what character is `'` I see you use it in the code, minetweaker is very weird with unicode, I suspect this is the issue, use `'`(May look the same, but it is different) instead

**Closed by jaredlll08** 2016-09-30 17:46 UTC
