### ISSUE TITLE
Some Recipes not working

### ISSUE THREAD

**Issue by yepidoodles** [jaredlll08/CraftTweaker#189] opened 2017-04-04 17:07 UTC
#### Issue Description:
Some of my recipes are not working - This is on SpongeForge Server on a modpack I created for my public server.

#### What happens:

After added recipes to scripts, some recipes do work and others don't - those which don't work don't throw any errors, they just don't come up in JEI and are uncraftable. There appears to be no correlation.

#### What you expected to happen:

All my recipes to work, obviously.

#### Scripts:

With recipes which doesn't work:
https://pastebin.com/k5BeWwV2  
https://pastebin.com/MR8CyUET  
https://pastebin.com/qqF6Kd4E  

With recipes which do work:
https://pastebin.com/c7fpbLph
https://pastebin.com/jqBtMzWv
https://pastebin.com/paVHHvZn

#### Minetweaker.log file:

https://pastebin.com/P8L1VWT3

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 2254
- Crafttweaker: 3.0.24
- SpongeForge: 2259
- Mods: https://pastebin.com/S3W9B77p

#### Your most recent log file where the issue was present: 

My latest log file for the server is over 200k lines long so I believe I've pasted the relevant info:
https://pastebin.com/N8zReAQs

Knowing my luck, this is something stupid I've missed, any help is appreciated.

- Alice
DragonTechMC

**Comment by jaredlll08** [comment] 2017-04-05 05:32
Can this be reproduced on a normal forge server?

**Comment by bookerthegeek** [comment] 2017-04-05 08:09
https://pastebin.com/k5BeWwV2 should be: (forgot to close the first emerald ore dictionary ingredient)
```
recipes.remove(<storagedrawers:upgradeStorage:4>);
recipes.addShaped(<storagedrawers:upgradeStorage:4>, [
 [<ore:gemEmerald>, <ore:stickWood>,     <ore:gemEmerald>],
 [<ore:stickWood>, <storagedrawers:upgradeStorage:3>, <ore:stickWood>],
 [<ore:gemEmerald>, <ore:stickWood>,     <ore:gemEmerald>]]);
```
https://pastebin.com/MR8CyUET should be: (Forgot to close the first ore dictionary for stone)
```
recipes.remove(<progressiveautomation:PlanterStone>);
recipes.addShaped(<progressiveautomation:PlanterStone>, [
  [<ore:stone>, <ore:stone>, <ore:stone>],
  [<ore:stone>, <progressiveautomation:Planter>, <ore:stone>],
  [<ore:stone>, <ore:bricksStone>, <ore:stone>]]);
```
https://pastebin.com/paVHHvZn should be: (Ender pearl ore dictionary has an underscore)
```
recipes.remove(<enderstorage:enderStorage>);
recipes.addShaped(<enderstorage:enderStorage>, [
  [<ore:rodBlaze>, <ore:blockWool>, <ore:rodBlaze>],
  [<ore:obsidian>, <ore:chestWood>, <ore:obsidian>],
  [<ore:rodBlaze>, <ore:ender_pearl>, <ore:rodBlaze>]]);
```

**Comment by yepidoodles** [comment] 2017-04-05 09:25
@bookerthegeek Thanks for pointing the missing `>`'s - I didn't think to look for those kinds of mistakes because it should have errored for that, no? The Progressive Automation and Storage Drawers ones now work fine.

Also `ore:enderpearl` is correct   
https://gyazo.com/8a09da9e7e14ad4c6258899d7145b1cc  
And again, if it was incorrect, it should have errored?  
There's nothing wrong with that EnderStorage script.

**Comment by bookerthegeek** [comment] 2017-04-05 10:21
Edited to reflect this. I have no idea as to why that does not work. 

@yepidoodles Can you place the enderchest in the world, dye all the colors a different color, then what is the output for MT hand?

**Comment by yepidoodles** [comment] 2017-04-05 10:36
Don't see how it helps but

`<enderstorage:enderStorage>.withTag({Frequency: {middle: 3, left: 2, right: 4}})`

**Comment by yepidoodles** [comment] 2017-04-05 10:50
As on my 1st server it works fine, I made a list of mods which are different between the servers (They have all the same plugins)

Mods 2nd server has but 1st doesn't:
- Agricraft
- Chameleon
- Chisel
- Cooking for Blockheads
- Decocraft
- Draws and Bits
- Earth Works
- Ender Zoo
- Flat Coloured Blocks
- Hunger Overhaul
- Infinity Lib
- Pam's Harvestcraft
- Progressive Automation
- Roguelike dungeons
- Ruins
- Spice of Life
- Storage Drawers
- Super Circuit Maker

Any chance any of these mods are interfering?

**Comment by bookerthegeek** [comment] 2017-04-05 13:34
Try This. If it does not work create a chest with all white and use that as the output stack
```
recipes.remove(<enderstorage:enderStorage>);
recipes.addShaped(<enderstorage:enderStorage>.withTag({Frequency: {middle: 0, left: 0, right: 0}}), [
	[<ore:rodBlaze>,<ore:blockWool>,<ore:rodBlaze>],
	[<ore:obsidian>,<ore:chestWood>,<ore:obsidian>],
	[<ore:rodBlaze>,<ore:enderpearl>,<ore:rodBlaze>]]);
```

**Comment by yepidoodles** [comment] 2017-04-05 18:24
Default all white ender chests are just `<enderstorage:enderStorage>` - I did try with the tags but that also didn't work.

**Comment by bookerthegeek** [comment] 2017-04-05 18:46
Link for the pack please?

**Comment by yepidoodles** [comment] 2017-04-05 20:02
https://www.technicpack.net/modpack/elbeta.705651

**Comment by HellishINC** [comment] 2017-05-16 04:07
I am (was, see "solution") also having this issue. I'm trying to remove the default recipes and add my own for Mekanism's steel/obsidian armor. No errors are being reported and _only_ the two chestplate do not work. I'm not using Sponge and I've tried 6 different Forge versions from 2815 (rec) to 2297 (current newest). All other scripts I have function correctly (BWM, MPS and IE). 

In 0remove.zs:
```
# Mekanism
recipes.remove(<mekanismtools:SteelHelmet>);
recipes.remove(<mekanismtools:ObsidianHelmet>);
#recipes.remove(<mekanismtools:SteelChestplate>); # Currently disabled removing vanilla or item is uncraftable
#recipes.remove(<mekanismtools:ObsidianChestplate>); # See above note
recipes.remove(<mekanismtools:SteelLeggings>);
recipes.remove(<mekanismtools:ObsidianLeggings>);
recipes.remove(<mekanismtools:SteelBoots>);
recipes.remove(<mekanismtools:ObsidianBoots>);
```

mek.zs:
```
# Steel armor
recipes.addShaped(<mekanismtools:SteelHelmet>,
  [[<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>],
  [<ore:plateIron>, <minecraft:leather_helmet>, <ore:plateIron>]]);
recipes.addShaped(<mekanismtools:SteelBoots>,
  [[<ore:plateSteel>, null, <ore:plateSteel>],
  [<ore:plateIron>, <minecraft:leather_boots>, <ore:plateIron>]]);
recipes.addShaped(<mekanismtools:SteelChestplate>,
  [[<ore:plateSteel>, <minecraft:leather_chestplate>, <ore:plateSteel>],
  [<ore:plateSteel>, null, <ore:plateSteel>],
  [<ore:plateIron>, <ore:plateSteel>, <ore:plateIron>]]);
recipes.addShaped(<mekanismtools:SteelLeggings>,
  [[<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>],
  [<ore:plateSteel>, <minecraft:leather_leggings>, <ore:plateSteel>],
  [<ore:plateIron>, null, <ore:plateIron>]]);
  
# Obsidian armor
recipes.addShaped(<mekanismtools:ObsidianHelmet>,
  [[<ore:itemCompressedObsidian>, <ore:itemCompressedObsidian>, <ore:itemCompressedObsidian>],
  [<ore:plateSteel>, <minecraft:leather_helmet>, <ore:plateSteel>]]);
recipes.addShaped(<mekanismtools:ObsidianBoots>,
  [[<ore:itemCompressedObsidian>, null, <ore:itemCompressedObsidian>],
  [<ore:plateSteel>, <minecraft:leather_boots>, <ore:plateSteel>]]);
recipes.addShaped(<mekanismtools:ObsidianChestplate>,
  [[<ore:itemCompressedObsidian>, <minecraft:leather_chestplate>, <ore:itemCompressedObsidian>],
  [<ore:itemCompressedObsidian>, <ore:itemCompressedObsidian>, <ore:itemCompressedObsidian>],
  [<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>]]);
```

Solution: Delete the entire minecraft instance and create a new one. This seems to have allowed the scripts to work. Why? I honestly have no clue.

**Comment by yepidoodles** [comment] 2017-05-16 06:53
`Delete the entire minecraft instance`, you mean the server? The map?

**Comment by HellishINC** [comment] 2017-05-16 07:47
No. The way MultiMC5 works is that you have separate minecraft "installations" that it keeps track of and manages. This way, you can have 3 1.10.2 instances ("installs") with different mod packs, one for 1.6.4, 2 for 1.11.2, etc.

What I did was save the script files and delete everything else, equivalent to the .minecraft folder on windows. Mind you, this is less than ideal as I know how have to sort through all the configs and update them again. I also didn't have any worlds aside from the flat testing so I didn't lose anything of value, aside from time.

**Comment by yepidoodles** [comment] 2017-05-16 07:57
Oh I assumed MultiMC5 was a Admin Panel, sorry. I'm glad this fix worked for you, but it certainly won't for me :/

**Comment by jaredlll08** [comment] 2017-07-19 08:59
Since I can't reproduce this, and an answer was never given as if this works without Spongeforge, I'm closing it.

**Closed by jaredlll08** 2017-07-19 08:59 UTC

**Comment by yepidoodles** [comment] 2017-07-19 15:14
> And idk about a normal forge server, but it doesn't work in Single player

**Comment by HellishINC** [comment] 2017-07-19 17:45
For what it's worth I haven't had this issue since and I'm betting it was most likely something I messed up.

**Comment by jaredlll08** [comment] 2017-07-19 18:30
> And idk about a normal forge server, but it doesn't work in Single player

Well sponge forge can be installed client side, so it not working in single player means nothing unless the single player test was done without spongeforge.

**Comment by yepidoodles** [comment] 2017-07-19 19:16
As far as I am aware, SpongeForge can not be installed client side... It is a server software/ mod. So no, SpongeForge was not installed client side.

**Comment by jaredlll08** [comment] 2017-07-19 19:52
can I get a list of the client mods?

```
/mt mods
``` should do

**Comment by HellishINC** [comment] 2017-07-20 01:10
> As far as I am aware, SpongeForge can not be installed client side...

![sponge](https://user-images.githubusercontent.com/4485158/28396002-7fc3849e-6cc6-11e7-82d4-c6036a834c66.png)

Please note I didn't do much testing as I have no real interest in running a "hacked together mess" and recreate the whole mcpc era nightmare.

**Comment by bookerthegeek** [comment] 2017-07-20 02:02
@jaredlll08 The mod list was posted in the OP unless changes is at https://pastebin.com/S3W9B77p

**Comment by jaredlll08** [comment] 2017-07-20 02:29
That list doesn't look generated though, so a generated list would be
better, with mod versions etc
