### ISSUE TITLE
Custom recipe multiple output, ghost input

### ISSUE THREAD

**Issue by drakray** [jaredlll08/CraftTweaker#165] opened 2017-03-01 15:07 UTC
#### Issue Description:
Custom recipe give a second output, and if InvTweak is installed, shift-clicking custom recipe give infinite result.
For example, using my script, putting a wood pressure plate on a crafting table, taking the 2 planks, 2 other plank will appear in the result slot. taking those 2 planks will stop behaviour. If using InvTweak, shift-clicking result slot will give 2 planks each time slot is shift-clicked.
Happens when using only CT and script, no other mod installed. (also with other mods)
Seems like there is a ghost input, as putting 1 stack of 1 stick with 1 stack of 2 stick will give a total of 3 planks. 1 click will consume 1 stick per stack, remain 1 stick; you can move the remaining stick in grid, plank will show in result slot as long as you don't overwrite the ghost stick.

#### What you expected to happen:
To not do that? Custom recipe should only give 1 output.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/keUXgRPJ

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/65Ei2Ymj

____
#### Affected Versions:

- Minecraft: 1.11.2
- Forge: 2233
- Crafttweaker: 3.0.22

#### Your most recent log file where the issue was present: 
Functionality error, not a logged error

**Comment by Rosethorns** [comment] 2017-03-07 00:44
I have been able to repeat this issue.
Forge: 13.20.0.2252
Crafttweaker: 3.0.22

**Comment by InterPlay02** [comment] 2017-03-07 00:55
I'm having the same issue, but with other items.
Forge: 13.20.0.2252
Crafttweaker: 3.0.22

**Comment by InterPlay02** [comment] 2017-03-07 23:26
Sorry, but... Can you CraftTweaker's guys re-upload this version of the mod again? (Or someone else)
**Crafttweaker: 3.0.22** for Minecraft 1.11.2.
I was almost finishing my modpack today, but my curse app just deleted the mod because it was telling me that the mod wasn't in curse forge anymore.

But the point is: I was able to "solve" this problem in my modpack, but if don't have the mod in curse forge, I can't upload it. And I don't have it anymore due to curse app deleting the mod.

**How I was able to "solve" the problem?** I simply add ".noReturn()" in all the items were this issue was happening. Cause this is not happening in all the items. Only in specific ones. And, when this happens to me, I added this ".noReturn()".

**Comment by drakray** [comment] 2017-03-07 23:47
I'm using CT 3.0.22 on Forge 2233, and I can say that ALL my custom recipe are showing the ghost behaviour

**Comment by InterPlay02** [comment] 2017-03-08 00:29
Well... I can't say if this is also true for me because I don't have the mod anymore. T.T
Can someone re-upload it for me, PLEASE??? T.T

**Comment by drakray** [comment] 2017-03-08 01:17
For testing [purpose](https://www.dropbox.com/s/i61hp9wlndrgbzp/CraftTweaker-1.11.2-3.0.22.jar?dl=0)
i'll bring it down on demand or when a new one comes out

**Comment by jaredlll08** [comment] 2017-03-08 02:01
Take it down please. 
It is obvious that he plans on actually releasing that version, which is a huge no go. There was a dupe bug in the old 1.11 versions, that is why they were taken down.

**Comment by InterPlay02** [comment] 2017-03-08 02:09
First: I can't release it, if you don't re-upload it to the curse forge. (And no, I don't want to release it in the Technic Launcher)
Second: Thanks for your upload.
Third: I test it out and, yes... As you said, all the items seems to be duplicating.
Last: The only thing that I can do for now is go back playing some more "The Hunter - Call of the wild" until the CraftTweaker Guys fix the problem.

Thanks for your attention.

**Comment by drakray** [comment] 2017-03-08 03:16
@jaredlll08 I deleted the file and removed the link

**Comment by drakray** [comment] 2017-03-09 14:53
as of 3.0.23, ghost are still present

**Comment by InterPlay02** [comment] 2017-03-09 17:38
Oh, man! Come on! I was so happy seconds ago, before I come here read you saying that. You just need to use that ".noReturn()" in one of the input items. Then it will works! Trust me! You only just need to write this in only one of the input items! And, for all the other recipes, you just need to remember to place this.
For example:
recipes.addShaped(<convenientadditions:ironwrench>, [[null, <ore:ingotIron>**.noReturn()**, null], [null, <ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, null, null]]);
As you can see, this recipe uses only iron Ingot. But, because I used the _.noReturn()_ in one the the input items, the recipe do not duplicate it self. Try it!

This works for me.

**Comment by drakray** [comment] 2017-03-09 18:59
1-Your trick is not a bug fix, it's a workaround, which I am not here for.

2-This trick is flawed, proof by using [this](http://pastebin.com/ddWZ4c36) script where crafting a slab will leave a pressure plate, and worse, if you put 2 row of stick, you will get all 3 item one after the other, +1 button. This example could cause trouble if it where not about wooden thing

Finally, I for one am using 27 zs file, with most having between 25 and 50 recipes, some close to 100, so adding noReturn after everything is tedious at least.

I understand that it work as a temporary workaround, but one must report that the supposedly fixed bug is not.

**Comment by jaredlll08** [comment] 2017-03-10 16:03
Are you guys testing this on a SSP world or multiplayer?

I can't reproduce this at all, having made 0 code changes since .23, this is what happens when I craft
http://i.blamejared.com/azz7F.webm

**Comment by drakray** [comment] 2017-03-10 16:07
I tested this in SSP and SMP. I'm using Forge 2233, if that may be a fault(more recent version crash some mods)
I will retry live

**Comment by drakray** [comment] 2017-03-10 16:40
[Video](https://drakray.tinytake.com/sf/MTQwNjEwM181MDYzOTIx) using .23, Forge 2233, and a bunch of mods showing bug

**Comment by jaredlll08** [comment] 2017-03-10 16:51
Can I get that exact script line please?

**Comment by drakray** [comment] 2017-03-10 16:54
`recipes.addShapeless(<minecraft:planks>,[<ore:stickWood>,<ore:stickWood>]);`

**Comment by raspopov** [comment] 2017-03-10 17:27
Mine duplicated recipes are: 
`recipes.addShapeless( <minecraft:paper> * 3, [ <minecraft:written_book:*> ] );`
 and 
`recipes.addShaped( <spartanshields:shield_basic_iron>, [ [ null, null, null ], [ <minecraft:iron_ingot>, <minecraft:shield:*>, <minecraft:iron_ingot> ], [ null, <minecraft:iron_ingot>, null ] ] );`
In fact all custom recipes produces dupes.

**Comment by jaredlll08** [comment] 2017-03-10 22:07
Here is it on my side, using the first script @raspopov posted
http://i.blamejared.com/Pm8PA.gif

Like I really cannot reproduce this, right now I'm thinking that maybe the build got messed, I'll take a look at that now

**Comment by jaredlll08** [comment] 2017-03-10 22:26
Sooo....
Seems the original build 23 didn't catch the new code.
Mind trying this one?
http://ci.blamejared.com/job/CraftTweaker/74/

**Comment by drakray** [comment] 2017-03-10 23:28
As far as I'm concerned, this version fix the Ghost Bug

**Comment by jaredlll08** [comment] 2017-03-12 22:32
Fixed in latest CrT (.24)

**Closed by jaredlll08** 2017-03-12 22:32 UTC
Labels: bug
