### ISSUE TITLE
Item duplication bug with transformDamage 

### ISSUE THREAD

**Issue by Matt-Sheridan** [jaredlll08/CraftTweaker#109] opened 2016-12-03 21:35 UTC
Recipes that use transformDamage return _two copies_ of the damaged item. Additionally, if you've got multiple copies of the other recipe ingredients in your crafting grid—meaning the materials which are just supposed to be consumed, not damaged—they _won't_ be consumed.

I've tested this without any other mods installed, and using the example recipe from the MineTweaker wiki.

`recipes.addShapeless(<minecraft:stick> * 3, [<minecraft:stone_axe>.transformDamage(), <ore:plankWood>]);`

So do things work differently in CraftTweaker, or is transformDamage broken by Minecraft 1.10.2? Or is it just me?

**Comment by jaredlll08** [comment] 2016-12-04 14:45
Duplicate of https://github.com/jaredlll08/CraftTweaker/issues/107 and fixed.

**Closed by jaredlll08** 2016-12-04 14:45 UTC
